version: '3.4'

services:
  sa2project:
    image: ${DOCKER_REGISTRY-}sa2project
    build:
      context: .
      dockerfile: SA2Project/Dockerfile
    depends_on:
        - db
    


  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Asd@123456
      - ACCEPT_EULA=Y
    ports:
        - "1433:1433"

  
    